### ISSUE TITLE
[EVENTOS] Problema na integração dos eventos: eventos sem informação

### ISSUE THREAD

**Issue by marina-hacklab** [Ethos-ti/SiteEthos#198]
O Nicholas está tentando acessar o evento da conferência ethos que foi na semana passada através do link do CRM: https://www.ethos.org.br/conteudo/inscricao-evento?id=1390
Porém o link, além de redirecionar para um evento que não é o esperado, ainda exibe a mensagem "Não encontramos a página procurada."

Tentei acessar o mesmo evento pela agenda e, agora na página com o título correto, o evento segue sem detalhes e com a mesma mensagem: "Não encontramos a página procurada."
https://www.ethos.org.br/evento/conferencia-ethos-360-sao-paulo-2024/

Mesmo problema em outro evento passado: https://www.ethos.org.br/evento/plantoes-de-duvidas-indicadores-ethos-setembro-2024/2024-09-09/
E em evento futuro: https://www.ethos.org.br/evento/roda-de-dialogo-papel-das-empresas-no-processo-eleitoral/

A minha suspeita é que seja relativo a essa atualização da Microsoft que ocorreu hoje.

**Comment by marinarcruz** [comment]
diagnóstico e resposta do Bruno ao cliente:

Bom dia @Fabio Ethos e @Nicholas Ethos!
O problema é que a API SOAP (que fica na máquina do sistema de indicadores, se não me engano) não está mais retornando o esperado. Nós não alteramos nada do lado do site, estamos recebendo este erro:

"Não foi possível atender sua solicitação. (System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Xrm.Tooling.Connector.CrmServiceClient.RetrieveMultiple(QueryBase query)
   at EthosWS.CRM.CRMServices.checkParticipant(String projeto, String name, String lastname, String email, String& errStr) in D:\I4D\OneDrive - I4D IT Solutions\Projetos\Ethos\prince\EthosWS\EthosWS\CRM\CRMServices.cs:line 2885
   at EthosWS.EthosWS.CheckParticipant(String projeto, String name, String lastname, String email) in D:\I4D\OneDrive - I4D IT Solutions\Projetos\Ethos\prince\EthosWS\EthosWS\EthosWS.asmx.cs:line 148)."

Não me parece que está associada ao problema do 2FA, nossa conta já tinha isso, mas esse login na API SOAP não usa essas credenciais. A conexão com a API do CRM, usada nas novas funcionalidades, está funcionando normalmente.
@Fabio Ethos Em casos como esse, nós somos solidários com o problema, mas entendemos que eles não da nossa responsabilidade. Como podemos ajudar vocês nessa solução?
